class Cliente {
  clientId: string = "";
  clientName: string = "";
  clientTaxId: string = "";
  address: string = "";
  isPosted: number = 0;
  phone: string = "";
  clientHhIdOld: string = "";
  contactCustomer: string = "";
  contactPhone: string = "";
  photo1: string = "";
  photo2: string = "";
  photo3: string = "";
  status: string = "NEW";
  isNew: number = 1;
  gps: string = "0,0";
  longitude: string = "";
  latitude: string = "";
  tags: Etiqueta[];
  createdFrom: string = "SONDA_POS";
  billingName: string = "";
  billingAddress: string = "";
  syncId: string = "";
  docSerie: string = "";
  docNum: string = "";
  tagsQty: number = 0;
  postedDatetime: Date = new Date();
  isPostedValidated: number = 0;
  canBuyOnCredit: boolean = false;
  currentAccountingInformation: CuentaCorrienteDeCliente = new CuentaCorrienteDeCliente();
  invoiceDueDate: Date = new Date();
  totalInvoicedIsOnCredit: boolean = false;
  creditAmount: number = 0;
  cashAmount: number = 0;
  invoiceHasCredit: boolean = false;
  overdueInvoices: Array<FacturaVencidaDeCliente> = [];
  totalAmountPayedOfOverdueInvoices: number = 0;
  totalAmountOfOpenInvoices: number = 0;
  paymentType: TipoDePagoDeFactura;
}
