class FacturaEncabezado {
    invoiceNum: number = 0;
    terms: string = "";
    postedDateTime: Date = new Date();
    clientId: string = "";
    clientName: string = "";
    posTerminal: string = "";
    gps: string = "0,0";
    totalAmount: number = 0.00;
    erpInvoiceId: number = 0;
    isPosted: number = 0;
    status: string = "";
    isCreditNote: number = 0;
    voidReason: string = "";
    voidNotes: string = "";
    voidInvoiceId: number = 0;
    printRequests: number = 0;
    printedCount: number = 0;
    authId: string = "";
    satSerie: string = "";
    change: number = 0.00;
    img1: string = "";
    img2: string = "";
    img3: string = "";
    consignmentId: number = 0;
    isPaidConsignment: number = 0;
    initialTaskImage: string = "";
    inPlanRoute: number = 0;
    idBo: number = 0;
    isPostedValidated: number = 0;
    detailQty: number = 0;
    handleTax: number = 0;
    taxPercent: number = 0.00;
    telephoneNumber: string = "";
    invoiceDetail: FacturaDetalle[];
}