class OrdenDeVentaDetalle {
    salesOrderId: number;
    sku: string;
    skuName: string;
    skuAvailable: number;
    lineSeq: number;
    qty: number;
    price: number;
    discount: number;
    totalLine: number;
    postedDatetime: string;
    serie: string;
    serie2: string;
    requeriesSerie: boolean;
    parentSeq: number;
    isActiveRoute: number;
    isPostedVoid: number;
    isVoid: boolean;
    comboReference : string;
    codePackUnit: string;
    totalAmountDisplay: number;
    docSerie: string;
    docNum: number;
    isBonus: number = 0;
    //available: number;
    handleDimension: boolean;
    long: number;
    isSaleByMultiple: boolean;
    multipleSaleQty: number;
    owner: string;
    ownerId: string;
    discountType: string; 
}